name: 'Terraform Module Workflow'

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  tf_build_deploy:
    uses: sknaresh2000/templates/.github/workflows/tf-vault.yml@main
    secrets: inherit